import React from "react";
import "./styles/globals.css"; // Assurez-vous que le chemin est correct
import Header from "./components/Header"; // Assurez-vous que le chemin est correct
import Footer from "./components/Footer"; // Assurez-vous que le chemin est correct
import CarouselComponent from "./components/CarouselComponent"; // Assurez-vous que le chemin est correct

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <CarouselComponent />
        <div className="container">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
